### ISSUE TITLE
create a regular Eclipse project

### ISSUE THREAD

**Issue by Furoryan** [alma2015BERLEMFOR/alma2015BERLEMFOR#7]
Create a regular Eclipse project named fr.univnantes.alma.oomph in a folder named resources

**Comment by Cr3aHal0** [comment]
Have a look at Pull request #8

**Comment by Furoryan** [comment]
OK

**Comment by Cr3aHal0** [comment]
Could you review the changes please ?

**Comment by Furoryan** [comment]
OK
